import { resolvePokeLoungeLocale } from "../poke-lounge-copy";

const COPY = {
  "ko-KR": {
    selected: "선택됨",
    selectPokemon: "교체할 포켓몬을 선택하세요",
    switchPokemon: "이 포켓몬으로 교체",
    noSwitch: "교체할 수 있는 포켓몬이 없습니다.",
    cannotSwitch: "지금은 교체할 수 없습니다",
    forcedSwitch: "다음에 내보낼 포켓몬을 선택하세요",
    chooseItem: "사용할 아이템을 선택하세요",
    useItem: "아이템 사용",
    noItems: "사용할 아이템이 없습니다.",
    unavailable: "지금은 사용할 수 없습니다",
    invalidSelection: "선택한 대상의 상태가 바뀌었습니다. 다시 선택해 주세요.",
    missing: "정보를 확인할 수 없습니다",
    target: "대상",
    activeTarget: "현재 전투 중인 포켓몬",
    opponentTarget: "야생 포켓몬",
    faintedTarget: "기절한 파티 포켓몬",
    runTitle: "도망칠까요?",
    runDescription: "현재 전투에서 도망을 시도합니다. 성공 여부는 게임 규칙에 따라 결정됩니다.",
    confirmRun: "도망 시도",
    keepBattle: "전투로 돌아가기",
    turn: "턴",
    timeLeft: "선택 시간",
    timeExpired: "다음 상태를 기다리는 중",
    ppEmpty: "PP 부족",
    emptyMove: "빈 기술",
    returnToGame: "게임으로 돌아가기",
    summary: "현재 게임",
    log: "전투 기록",
    noLog: "아직 전투 기록이 없습니다.",
    chooseAgain: "다시 선택",
    details: "상세",
  },
  "en-US": {
    selected: "Selected",
    selectPokemon: "Choose a Pokémon to switch in",
    switchPokemon: "Switch to this Pokémon",
    noSwitch: "No Pokémon can switch in.",
    cannotSwitch: "Cannot switch now",
    forcedSwitch: "Choose the next Pokémon to send out",
    chooseItem: "Choose an item to use",
    useItem: "Use item",
    noItems: "No items available.",
    unavailable: "Unavailable now",
    invalidSelection: "This selection has changed. Please choose again.",
    missing: "Information unavailable",
    target: "Target",
    activeTarget: "Active Pokémon",
    opponentTarget: "Wild Pokémon",
    faintedTarget: "Fainted party Pokémon",
    runTitle: "Run from this battle?",
    runDescription: "Attempt to escape this battle. Success depends on the game rules.",
    confirmRun: "Attempt escape",
    keepBattle: "Return to battle",
    turn: "Turn",
    timeLeft: "Time left",
    timeExpired: "Waiting for the next state",
    ppEmpty: "No PP",
    emptyMove: "Empty move",
    returnToGame: "Return to game",
    summary: "Current game",
    log: "Battle log",
    noLog: "No battle events yet.",
    chooseAgain: "Choose again",
    details: "Details",
  },
  "ja-JP": {
    selected: "選択中",
    selectPokemon: "交代するポケモンを選んでください",
    switchPokemon: "このポケモンに交代",
    noSwitch: "交代できるポケモンがいません。",
    cannotSwitch: "今は交代できません",
    forcedSwitch: "次に出すポケモンを選んでください",
    chooseItem: "使う道具を選んでください",
    useItem: "道具を使う",
    noItems: "使える道具がありません。",
    unavailable: "今は使えません",
    invalidSelection: "選んだ対象の状態が変わりました。選び直してください。",
    missing: "情報を確認できません",
    target: "対象",
    activeTarget: "戦闘中のポケモン",
    opponentTarget: "野生のポケモン",
    faintedTarget: "ひんしの手持ちポケモン",
    runTitle: "逃げますか？",
    runDescription: "この戦闘から逃げようとします。成功するかはゲームのルールで決まります。",
    confirmRun: "逃げる",
    keepBattle: "戦闘に戻る",
    turn: "ターン",
    timeLeft: "残り時間",
    timeExpired: "次の状態を待っています",
    ppEmpty: "PP不足",
    emptyMove: "技なし",
    returnToGame: "ゲームに戻る",
    summary: "現在のゲーム",
    log: "戦闘の記録",
    noLog: "まだ記録はありません。",
    chooseAgain: "選び直す",
    details: "詳細",
  },
};
export function getMobileUiCopy(locale: string) {
  return COPY[resolvePokeLoungeLocale(locale)];
}
