/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 서버 상태 확인 */
    get: operations["AppController_getHello"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** API 헬스 체크 */
    get: operations["AppController_getHealth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/game/result": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 게임 결과 생성 및 랭킹 확인 */
    post: operations["GameController_createResult"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/game/poke-lounge/state": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Poke Lounge 상태 조회 */
    get: operations["GameController_getPokeLoungeState"];
    /** Poke Lounge 상태 저장 */
    put: operations["GameController_savePokeLoungeState"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/game/ranking": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 게임별 Top 10 랭킹 조회
     * @description POKE_LOUNGE는 영속 기록을 만들지 않아 빈 배열을 반환합니다.
     */
    get: operations["GameController_getRanking"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/game/result/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 게임 결과 상세 조회 */
    get: operations["GameController_getGameResult"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/poke-lounge/rom-data": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** ROM에서 추출한 Poke Lounge 게임 데이터 조회 */
    get: operations["PokeLoungeController_getRomData"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/poke-lounge/shops/basic/items": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Poke Lounge 일반 상점 판매 목록 조회 */
    get: operations["PokeLoungeController_getBasicShopItemIds"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/poke-lounge/shops/premium/items": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Poke Lounge 희귀 상점 판매 목록 조회 */
    get: operations["PokeLoungeController_getPremiumShopItemIds"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/poke-lounge/rooms": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["PokeLoungeController_createRoom"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/poke-lounge/rooms/{roomCode}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["PokeLoungeController_getRoom"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/poke-lounge/rooms/{roomCode}/competitive-seat": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["PokeLoungeController_bindCompetitiveSeat"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/poke-lounge/rooms/{roomCode}/matches/{matchId}/actions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["PokeLoungeController_submitCompetitiveAction"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/poke-lounge/rooms/{roomCode}/matches/{matchId}/session-actions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["PokeLoungeController_submitSessionCompetitiveAction"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/poke-lounge/rooms/quick-play": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["PokeLoungeController_quickPlay"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/poke-lounge/rooms/{roomCode}/join": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["PokeLoungeController_joinRoom"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/poke-lounge/rooms/{roomCode}/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["PokeLoungeController_setReady"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/poke-lounge/rooms/{roomCode}/round-ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["PokeLoungeController_setRoundReady"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/poke-lounge/rooms/{roomCode}/start": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["PokeLoungeController_startRoom"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/poke-lounge/rooms/{roomCode}/party-snapshot": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["PokeLoungeController_updatePartySnapshot"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/poke-lounge/rooms/{roomCode}/result": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Submit a casual Poke Lounge result
     * @description Client-reported room results remain unverified and cannot create verified trust or public ranking entries.
     */
    post: operations["PokeLoungeController_submitResult"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/poke-lounge/rooms/{roomCode}/leave": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["PokeLoungeController_leaveRoom"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    HealthCheckResponseDto: {
      /** @example ok */
      status: string;
      /**
       * @description API process uptime in seconds
       * @example 123.45
       */
      uptime: number;
      /**
       * @description Health check response time in ISO 8601 format
       * @example 2026-07-05T00:00:00.000Z
       */
      timestamp: string;
    };
    /**
     * @description 서버에 등록된 게임 타입. 게임별 점수 정책은 서버에서 적용된다.
     * @enum {string}
     */
    GameType: "SKY_DROP" | "POKE_LOUNGE";
    CreateGameHistoryDto: {
      /**
       * @description 게임별 서버 정책으로 최종 검증되는 정수 점수. DTO는 전체 게임 타입의 제출 envelope만 검증한다.
       * @example 8500
       */
      score: number;
      /**
       * @description 플레이 시간(초). 제출되면 게임별 서버 정책의 점수 대비 비정상 속도 검증에 사용된다.
       * @example 120
       */
      playTime?: number;
      /**
       * @description 서버에 등록된 게임 타입. 게임별 점수 정책은 서버에서 적용된다.
       * @example SKY_DROP
       */
      gameType: components["schemas"]["GameType"];
    };
    GameHistoryUserDto: {
      /**
       * @description 사용자 닉네임
       * @example 홍길동
       */
      displayName: string;
    };
    GameHistoryResponseDto: {
      /**
       * @description 게임 기록 ID (UUID)
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      id: string;
      /**
       * @description 점수
       * @example 100
       */
      score: number;
      /**
       * @description 게임 타입
       * @example SKY_DROP
       * @enum {string}
       */
      gameType: "SKY_DROP" | "POKE_LOUNGE";
      /**
       * Format: date-time
       * @description 생성 일시
       * @example 2024-01-30T12:00:00.000Z
       */
      createdAt: string;
      /** @description 사용자 정보 */
      user: components["schemas"]["GameHistoryUserDto"];
      /**
       * @description 현재 등수 (1부터 시작, 랭킹 외 시 null)
       * @example 1
       */
      rank?: number | null;
      /**
       * @description 유저의 역대 최고 점수
       * @example 1200
       */
      bestScore?: number | null;
      /**
       * @description 전체 기간 랭킹
       * @example 42
       */
      allTimeRank?: number | null;
      /**
       * @description 금주 랭킹 (KST 월요일 0시 ~ 일요일 24시 기준)
       * @example 5
       */
      weeklyRank?: number | null;
    };
    SavePokeLoungeStateDto: {
      /**
       * @description Poke Lounge 클라이언트의 현재 저장 상태
       * @example {
       *       "trainer": {
       *         "x": 12,
       *         "y": 3
       *       },
       *       "party": [
       *         "pikachu",
       *         "eevee"
       *       ]
       *     }
       */
      state: {
        [key: string]: unknown;
      };
      /**
       * @description 마지막으로 조회하거나 저장한 서버 revision. 신규 저장은 0이며, 값이 일치할 때만 갱신됩니다. 생략은 구버전 Web의 신규 저장 또는 revision 0 마이그레이션 행의 1회 전환에만 허용됩니다.
       * @example 3
       */
      expectedRevision?: number;
      /**
       * @description 진단용 클라이언트 갱신 시각. 저장 순서 판정에는 사용하지 않습니다.
       * @example 2026-07-08T12:00:00.000Z
       */
      clientUpdatedAt?: string;
    };
    PokeLoungeStateResponseDto: {
      /**
       * @description Poke Lounge 상태 저장 ID
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      id: string;
      /**
       * @description 상태를 저장한 사용자 ID
       * @example google-sub-id
       */
      userId: string;
      /** @description Poke Lounge 클라이언트의 저장 상태 */
      state: {
        [key: string]: unknown;
      };
      /**
       * @description 서버가 원자적으로 증가시키는 저장 revision
       * @example 4
       */
      revision: number;
      /**
       * Format: date-time
       * @description 서버 저장 생성 시각
       * @example 2026-07-08T12:00:01.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description 서버 저장 갱신 시각
       * @example 2026-07-08T12:00:02.000Z
       */
      updatedAt: string;
      /**
       * @description 클라이언트 기준 상태 갱신 시각
       * @example 2026-07-08T12:00:00.000Z
       */
      clientUpdatedAt?: Record<string, never> | null;
    };
    GameRankingHistoryDto: {
      /**
       * @description 점수
       * @example 100
       */
      score: number;
      /**
       * @description 순위
       * @example 1
       */
      rank: number;
      /**
       * Format: date-time
       * @description 생성 일시
       * @example 2024-01-30T12:00:00.000Z
       */
      createdAt: string;
      /** @description 공개 사용자 정보 */
      user: components["schemas"]["GameHistoryUserDto"];
    };
    PokeLoungeRepresentativePokemonDto: {
      /** @example 25 */
      speciesId: number;
      /** @example 12 */
      level: number;
      /** @example 18 */
      currentHp: number;
      /** @example 30 */
      maxHp: number;
    };
    PokeLoungePartySnapshotDto: {
      /** @example player-a */
      playerId: string;
      /** @example Player A */
      displayName?: string;
      representativePokemon: components["schemas"]["PokeLoungeRepresentativePokemonDto"];
      /** @example 1 */
      partySize: number;
      /** @example 1720000002000 */
      updatedAtMs: number;
    };
    CompetitiveMoveStateDto: {
      moveId: number;
      pp: number;
    };
    CompetitiveBattleStatStagesDto: {
      attack: number;
      defense: number;
      specialAttack: number;
      specialDefense: number;
      speed: number;
      accuracy: number;
      evasion: number;
    };
    CompetitiveCombatantStateDto: {
      speciesId: number;
      slotIndex: number;
      level: number;
      maxHp: number;
      currentHp: number;
      /** @enum {string} */
      status: "normal" | "poisoned" | "burned" | "paralyzed" | "fainted";
      statStages: components["schemas"]["CompetitiveBattleStatStagesDto"];
      moves: components["schemas"]["CompetitiveMoveStateDto"][];
    };
    CompetitivePlayerStateDto: {
      playerId: string;
      activeSlotIndex: number;
      team: components["schemas"]["CompetitiveCombatantStateDto"][];
    };
    CompetitiveTerminalResultDto: {
      winnerPlayerId: string;
      loserPlayerId: string;
      /** @enum {string} */
      reason: "faint" | "forfeit" | "timeout";
      scoreByPlayerId: {
        [key: string]: 50 | 100;
      };
    };
    CompetitiveBattleStateDto: {
      /**
       * @example 2
       * @enum {number}
       */
      rulesetVersion: 2;
      turn: number;
      participantIds: string[];
      playersById: {
        [key: string]: components["schemas"]["CompetitivePlayerStateDto"];
      };
      terminal: components["schemas"]["CompetitiveTerminalResultDto"] | null;
    };
    CompetitiveActionResponseDto: {
      matchId: string;
      /** @example game-round-1-bracket-1-match-1 */
      bracketMatchId: string;
      /** @enum {string} */
      kind: "ranked-head-to-head" | "tournament-unranked";
      assignmentRevision: number;
      rulesetVersion: number;
      rulesetHash: string;
      currentTurn: number;
      turnEndsAtMs: number;
      /** @enum {string} */
      status: "pending" | "active" | "completed";
      /** Format: uuid */
      terminalEventId: string | null;
      terminalRoomRevision: number | null;
      playerIds: string[];
      stateHash: string;
      currentState: components["schemas"]["CompetitiveBattleStateDto"];
      submittedPlayerIds: string[];
      terminal: components["schemas"]["CompetitiveTerminalResultDto"] | null;
    };
    CompetitiveTerminalTransitionDto: {
      /** Format: uuid */
      terminalEventId: string;
      terminalRoomRevision: number;
      projection: components["schemas"]["CompetitiveActionResponseDto"];
    };
    PokeLoungeRoomParticipantDto: {
      /** @example player-a */
      playerId: string;
      /** @example Player A */
      displayName: string;
      /**
       * @example participant
       * @enum {string}
       */
      role: "participant" | "spectator";
      /** @example true */
      ready: boolean;
      /** @example true */
      connected: boolean;
      /** @example 1720000000000 */
      joinedAtMs: number;
      /** @example 1720000005000 */
      leftAtMs?: number;
    };
    PokeLoungeRoundDto: {
      /** @example 1 */
      index: number;
      /**
       * @example waiting
       * @enum {string}
       */
      phase: "waiting" | "round-started" | "tournament" | "completed";
      /** @example 60000 */
      durationMs: number;
      /** @example 1720000000000 */
      startedAtMs: number | null;
      /** @example 1720000060000 */
      endsAtMs: number | null;
    };
    PokeLoungeTournamentParticipantDto: {
      /** @example player-a */
      playerId: string;
      /** @example Player A */
      displayName: string;
      /** @example 1 */
      seed: number;
    };
    PokeLoungeTournamentMatchDto: {
      /** @example game-round-1-bracket-1-match-1 */
      matchId: string;
      /** @example 1 */
      roundNumber: number;
      /** @example 1 */
      matchNumber: number;
      participantA: components["schemas"]["PokeLoungeTournamentParticipantDto"];
      participantB: components["schemas"]["PokeLoungeTournamentParticipantDto"];
      /**
       * @example [
       *       "player-a",
       *       "player-b"
       *     ]
       */
      participantIds: string[];
      /**
       * @example ready
       * @enum {string}
       */
      status: "ready" | "completed";
      /** @example player-a */
      winnerPlayerId: string | null;
      /** @example player-b */
      loserPlayerId: string | null;
      /**
       * @example faint
       * @enum {string|null}
       */
      resultReason: "faint" | "timeout" | "forfeit" | "run" | "capture" | null;
      /** @example 1720000060000 */
      completedAtMs: number | null;
    };
    PokeLoungeTournamentByeDto: {
      /** @example game-round-1-bracket-1-bye-1 */
      byeId: string;
      /** @example 1 */
      roundNumber: number;
      /** @example 1 */
      slotNumber: number;
      entrant: components["schemas"]["PokeLoungeTournamentParticipantDto"];
    };
    PokeLoungeTournamentRoundSlotDto: {
      /** @enum {string} */
      kind: "match" | "bye";
      /** @example game-round-1-bracket-1-match-1 */
      matchId?: string;
      /** @example game-round-1-bracket-1-bye-1 */
      byeId?: string;
    };
    PokeLoungeTournamentRoundDto: {
      /** @example 1 */
      roundNumber: number;
      matches: components["schemas"]["PokeLoungeTournamentMatchDto"][];
      byes: components["schemas"]["PokeLoungeTournamentByeDto"][];
      slots: components["schemas"]["PokeLoungeTournamentRoundSlotDto"][];
    };
    PokeLoungeTournamentEliminationDto: {
      /** @example player-b */
      playerId: string;
      /** @example Player B */
      displayName: string;
      /** @example 2 */
      seed: number;
      /** @example 1 */
      roundNumber: number;
      /** @example game-round-1-bracket-1-match-1 */
      matchId: string;
      /** @example 1 */
      order: number;
    };
    PokeLoungeTournamentBracketDto: {
      /**
       * @example 1
       * @enum {number}
       */
      version: 1;
      /** @example 1 */
      gameRoundIndex: number;
      /** @enum {string} */
      status: "in-progress" | "completed";
      participants: components["schemas"]["PokeLoungeTournamentParticipantDto"][];
      currentRound: components["schemas"]["PokeLoungeTournamentRoundDto"] | null;
      completedRounds: components["schemas"]["PokeLoungeTournamentRoundDto"][];
      eliminations: components["schemas"]["PokeLoungeTournamentEliminationDto"][];
      /** @example player-a */
      championPlayerId: string | null;
    };
    PokeLoungeTournamentDto: {
      /**
       * @example 2
       * @enum {number}
       */
      version: 2;
      bracket: components["schemas"]["PokeLoungeTournamentBracketDto"] | null;
      /** @example game-round-1-bracket-1-match-1 */
      activeMatchId: string | null;
      /** @enum {string|null} */
      activeMatchAuthority: "casual" | "server" | null;
      /**
       * @example {
       *       "player-a": 100,
       *       "player-b": 50
       *     }
       */
      cumulativeScores: {
        [key: string]: number;
      };
    };
    PokeLoungeFinalStandingDto: {
      /** @example player-a */
      playerId: string;
      /** @example Player A */
      displayName: string;
      /** @example 1 */
      rank: number;
      /** @example 100 */
      score: number;
    };
    PokeLoungeRoomResponseDto: {
      /** @example ROOM01 */
      roomCode: string;
      /**
       * @example public
       * @enum {string}
       */
      visibility: "public" | "private";
      /**
       * @example waiting
       * @enum {string}
       */
      status: "waiting" | "round-started" | "tournament" | "completed" | "closed";
      /**
       * @example competitive-party-not-ready
       * @enum {string}
       */
      closeReason?: "legacy-room-restart-required" | "competitive-party-not-ready";
      /** @example 1720000000000 */
      createdAtMs: number;
      /** @example 1720000001000 */
      updatedAtMs: number;
      /** @example 3 */
      revision: number;
      /** @example 1720001800000 */
      expiresAtMs: number;
      /** @example player-a */
      hostPlayerId: string | null;
      participants: components["schemas"]["PokeLoungeRoomParticipantDto"][];
      partySnapshots: {
        [key: string]: components["schemas"]["PokeLoungePartySnapshotDto"];
      };
      round: components["schemas"]["PokeLoungeRoundDto"];
      tournament: components["schemas"]["PokeLoungeTournamentDto"];
      finalStandings: components["schemas"]["PokeLoungeFinalStandingDto"][];
      competitiveTransitions: components["schemas"]["CompetitiveTerminalTransitionDto"][];
      competitiveAssignments: components["schemas"]["CompetitiveActionResponseDto"][];
      competitive?: components["schemas"]["CompetitiveActionResponseDto"];
    };
    PokeLoungeRoomConflictResponseDto: {
      /** @example 409 */
      statusCode: number;
      /** @enum {string} */
      code: "POKE_LOUNGE_REVISION_CONFLICT" | "POKE_LOUNGE_IDEMPOTENCY_CONFLICT";
      /** @example Poke Lounge room revision conflict */
      message: string;
      snapshot: components["schemas"]["PokeLoungeRoomResponseDto"];
    };
    PokeLoungeRoomFullResponseDto: {
      /** @example 409 */
      statusCode: number;
      /** @enum {string} */
      code: "POKE_LOUNGE_ROOM_FULL";
      /** @example Poke Lounge room is full */
      message: string;
    };
    PokeLoungeRomDocumentDto: {
      /** @enum {string} */
      documentKey: "pokemon-data" | "item-data" | "level-up-move-table" | "growth-table";
      /**
       * @example 1
       * @enum {number}
       */
      schemaVersion: 1;
      romSha1: string;
      contentSha256: string;
      payload: {
        [key: string]: unknown;
      };
    };
    PokeLoungeRomDataResponseDto: {
      documents: components["schemas"]["PokeLoungeRomDocumentDto"][];
    };
    CreatePokeLoungeRoomDto: {
      /** @example ABC234 */
      roomCode?: string;
      /** @example player-a */
      playerId?: string;
      /** @example session-a */
      sessionId: string;
      /** @example user-123 */
      userId?: string;
      /** @example Player A */
      displayName?: string;
      /**
       * @description Test-only override; production preparation is fixed at 180000ms
       * @example 180000
       */
      roundDurationMs?: number;
    };
    BindCompetitiveSeatDto: {
      /** @example session-a */
      sessionId: string;
    };
    CompetitiveAssignmentResponseDto: {
      matchId: string;
      /** @example game-round-1-bracket-1-match-1 */
      bracketMatchId: string;
      /** @enum {string} */
      kind: "ranked-head-to-head" | "tournament-unranked";
      assignmentRevision: number;
      rulesetVersion: number;
      rulesetHash: string;
      currentTurn: number;
      turnEndsAtMs: number;
      /** @enum {string} */
      status: "pending" | "active" | "completed";
      /** Format: uuid */
      terminalEventId: string | null;
      terminalRoomRevision: number | null;
      playerIds: string[];
      stateHash: string;
      currentState: components["schemas"]["CompetitiveBattleStateDto"];
      submittedPlayerIds: string[];
      terminal: components["schemas"]["CompetitiveTerminalResultDto"] | null;
    };
    CompetitiveActionDto: {
      /** @enum {string} */
      kind: "move" | "switch";
      moveId?: number | string;
      slotIndex?: number;
    };
    SubmitCompetitiveActionDto: {
      assignmentRevision: number;
      turn: number;
      /** Format: uuid */
      clientCommandId: string;
      action: components["schemas"]["CompetitiveActionDto"];
    };
    SubmitSessionCompetitiveActionDto: {
      assignmentRevision: number;
      turn: number;
      /** Format: uuid */
      clientCommandId: string;
      action: components["schemas"]["CompetitiveActionDto"];
      sessionId: string;
    };
    JoinPokeLoungeRoomDto: {
      /** @example player-b */
      playerId?: string;
      /** @example session-b */
      sessionId: string;
      /** @example user-456 */
      userId?: string;
      /** @example Player B */
      displayName?: string;
    };
    SetPokeLoungeReadyDto: {
      /** @example player-a */
      playerId: string;
      /** @example session-a */
      sessionId: string;
      /** @example true */
      ready: boolean;
    };
    SetPokeLoungeRoundReadyDto: {
      /** @example player-a */
      playerId: string;
      /** @example session-a */
      sessionId: string;
      /** @example 1 */
      roundIndex: number;
    };
    StartPokeLoungeRoomDto: {
      /** @example player-a */
      playerId: string;
      /** @example session-a */
      sessionId: string;
    };
    CompetitiveIndividualValuesDto: {
      /** @example 31 */
      hp: number;
      /** @example 20 */
      attack: number;
      /** @example 25 */
      defense: number;
      /** @example 17 */
      specialAttack: number;
      /** @example 23 */
      specialDefense: number;
      /** @example 19 */
      speed: number;
    };
    CompetitivePartyMoveDto: {
      /** @example 55 */
      moveId: number;
      /** @example 25 */
      pp: number;
    };
    CompetitivePartyMemberDto: {
      /** @example 0 */
      slotIndex: number;
      /** @example 7 */
      speciesId: number;
      /** @example 11 */
      level: number;
      /** @example 30 */
      currentHp: number;
      /**
       * @example normal
       * @enum {string}
       */
      status: "normal" | "poisoned" | "burned" | "paralyzed" | "fainted";
      individualValues: components["schemas"]["CompetitiveIndividualValuesDto"];
      moves: components["schemas"]["CompetitivePartyMoveDto"][];
    };
    CompetitivePartyDto: {
      /**
       * @example 2
       * @enum {number}
       */
      version: 2;
      /** @example 0 */
      activeSlotIndex: number;
      members: components["schemas"]["CompetitivePartyMemberDto"][];
    };
    UpdatePokeLoungePartySnapshotDto: {
      /** @example player-a */
      playerId: string;
      /** @example session-a */
      sessionId: string;
      /** @example Player A */
      displayName?: string;
      competitiveParty: components["schemas"]["CompetitivePartyDto"];
    };
    SubmitPokeLoungeMatchResultDto: {
      /** @example player-a */
      reportingPlayerId: string;
      /** @example session-a */
      reportingSessionId: string;
      /** @example game-round-1-bracket-1-match-1 */
      matchId: string;
      /** @example player-a */
      winnerPlayerId: string;
      /** @example player-b */
      loserPlayerId: string;
      /**
       * @example faint
       * @enum {string}
       */
      reason: "faint" | "timeout" | "forfeit";
    };
    LeavePokeLoungeRoomDto: {
      /** @example player-a */
      playerId: string;
      /** @example session-a */
      sessionId: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AppController_getHello: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 서버가 정상적으로 동작 중임을 나타내는 메시지 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {boolean} */
            success: true;
            /** @example Hello World! */
            data: string;
          };
        };
      };
    };
  };
  AppController_getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description API 프로세스가 정상적으로 요청을 처리할 수 있는 상태 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["HealthCheckResponseDto"];
          };
        };
      };
    };
  };
  GameController_createResult: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateGameHistoryDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["GameHistoryResponseDto"];
          };
        };
      };
    };
  };
  GameController_getPokeLoungeState: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["PokeLoungeStateResponseDto"];
          };
        };
      };
      /** @description 저장된 Poke Lounge 상태가 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  GameController_savePokeLoungeState: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SavePokeLoungeStateDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["PokeLoungeStateResponseDto"];
          };
        };
      };
    };
  };
  GameController_getRanking: {
    parameters: {
      query: {
        /** @description 조회할 게임 타입 */
        gameType: components["schemas"]["GameType"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["GameRankingHistoryDto"][];
          };
        };
      };
    };
  };
  GameController_getGameResult: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 공유된 게임 결과 조회 (로그인 필요 없음) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["GameHistoryResponseDto"];
          };
        };
      };
    };
  };
  PokeLoungeController_getRomData: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["PokeLoungeRomDataResponseDto"];
          };
        };
      };
      /** @description 필수 ROM 문서가 없거나 무결하지 않음 */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PokeLoungeController_getBasicShopItemIds: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {boolean} */
            success: true;
            data: number[];
          };
        };
      };
      /** @description 일반 상점 판매 목록이 없거나 무결하지 않음 */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PokeLoungeController_getPremiumShopItemIds: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {boolean} */
            success: true;
            data: number[];
          };
        };
      };
      /** @description 희귀 상점 판매 목록이 없거나 무결하지 않음 */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PokeLoungeController_createRoom: {
    parameters: {
      query?: never;
      header: {
        "If-Match-Revision": string;
        "X-Idempotency-Key": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatePokeLoungeRoomDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["PokeLoungeRoomResponseDto"];
          };
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["PokeLoungeRoomConflictResponseDto"]
            | components["schemas"]["PokeLoungeRoomFullResponseDto"];
        };
      };
    };
  };
  PokeLoungeController_getRoom: {
    parameters: {
      query?: {
        afterRevision?: number;
      };
      header?: never;
      path: {
        roomCode: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["PokeLoungeRoomResponseDto"];
          };
        };
      };
    };
  };
  PokeLoungeController_bindCompetitiveSeat: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        roomCode: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BindCompetitiveSeatDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["CompetitiveAssignmentResponseDto"];
          };
        };
      };
    };
  };
  PokeLoungeController_submitCompetitiveAction: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        roomCode: string;
        matchId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SubmitCompetitiveActionDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["CompetitiveActionResponseDto"];
          };
        };
      };
    };
  };
  PokeLoungeController_submitSessionCompetitiveAction: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        roomCode: string;
        matchId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SubmitSessionCompetitiveActionDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["CompetitiveActionResponseDto"];
          };
        };
      };
    };
  };
  PokeLoungeController_quickPlay: {
    parameters: {
      query?: never;
      header: {
        "X-Idempotency-Key": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["JoinPokeLoungeRoomDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["PokeLoungeRoomResponseDto"];
          };
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PokeLoungeRoomFullResponseDto"];
        };
      };
    };
  };
  PokeLoungeController_joinRoom: {
    parameters: {
      query?: never;
      header: {
        "If-Match-Revision": string;
        "X-Idempotency-Key": string;
      };
      path: {
        roomCode: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["JoinPokeLoungeRoomDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["PokeLoungeRoomResponseDto"];
          };
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["PokeLoungeRoomConflictResponseDto"]
            | components["schemas"]["PokeLoungeRoomFullResponseDto"];
        };
      };
    };
  };
  PokeLoungeController_setReady: {
    parameters: {
      query?: never;
      header: {
        "If-Match-Revision": string;
        "X-Idempotency-Key": string;
      };
      path: {
        roomCode: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetPokeLoungeReadyDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["PokeLoungeRoomResponseDto"];
          };
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PokeLoungeRoomConflictResponseDto"];
        };
      };
    };
  };
  PokeLoungeController_setRoundReady: {
    parameters: {
      query?: never;
      header: {
        "X-Idempotency-Key": string;
      };
      path: {
        roomCode: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetPokeLoungeRoundReadyDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["PokeLoungeRoomResponseDto"];
          };
        };
      };
    };
  };
  PokeLoungeController_startRoom: {
    parameters: {
      query?: never;
      header: {
        "If-Match-Revision": string;
        "X-Idempotency-Key": string;
      };
      path: {
        roomCode: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StartPokeLoungeRoomDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["PokeLoungeRoomResponseDto"];
          };
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PokeLoungeRoomConflictResponseDto"];
        };
      };
    };
  };
  PokeLoungeController_updatePartySnapshot: {
    parameters: {
      query?: never;
      header: {
        "If-Match-Revision": string;
        "X-Idempotency-Key": string;
      };
      path: {
        roomCode: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdatePokeLoungePartySnapshotDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["PokeLoungeRoomResponseDto"];
          };
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PokeLoungeRoomConflictResponseDto"];
        };
      };
    };
  };
  PokeLoungeController_submitResult: {
    parameters: {
      query?: never;
      header: {
        "If-Match-Revision": string;
        "X-Idempotency-Key": string;
      };
      path: {
        roomCode: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SubmitPokeLoungeMatchResultDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["PokeLoungeRoomResponseDto"];
          };
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PokeLoungeRoomConflictResponseDto"];
        };
      };
    };
  };
  PokeLoungeController_leaveRoom: {
    parameters: {
      query?: never;
      header: {
        "If-Match-Revision": string;
        "X-Idempotency-Key": string;
      };
      path: {
        roomCode: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LeavePokeLoungeRoomDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["PokeLoungeRoomResponseDto"];
          };
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PokeLoungeRoomConflictResponseDto"];
        };
      };
    };
  };
}
