import { resolvePokeLoungeLocale } from "../../../poke-lounge-copy";

const copy = {
  "ko-KR": {
    eyebrow: "함께하는 모험",
    room: "방 코드",
    duration: "탐험 준비 시간",
    me: "나",
    players: "함께할 트레이너",
    spectators: "관전자",
    human: "트레이너",
    invite: "초대 링크 복사",
    inviteHint: "링크를 보내 친구를 초대하세요.",
    readyCount: (ready: number, total: number) => `준비 ${ready}/${total}`,
    ownNotReady: "함께할 준비가 되었나요?",
    start: "게임 시작",
    returnToLobby: "대기실로 돌아가기",
    hostWaiting: "친구를 초대하고 모두 준비되면 시작하세요.",
    autoFill: "빈자리는 시작할 때 AI가 채워요.",
    info: "게임 안내",
    closeInfo: "참가자 보기",
    next: "다음 단계",
    empty: "참가자를 기다리고 있어요.",
    joinTitle: "대기실에 참여하기",
    createTitle: "모험을 시작할 준비",
    joinHint: "친구에게 보여 줄 이름을 정하고 함께 입장하세요.",
    createHint: "이름을 정하면 친구를 초대할 수 있는 대기실이 열립니다.",
    enter: "대기실 입장",
    create: "대기실 만들기",
    back: "돌아가기",
    pending: "입장하는 중…",
    readyPending: "준비 반영 중…",
    startPending: "시작하는 중…",
    aiPending: "AI 반영 중…",
    stepLobby: "대기실",
    stepPokemon: "포켓몬 선택",
    stepExplore: "탐험 시작",
    spectatorHint: "관전 중입니다. 참가자들의 준비를 기다려 주세요.",
    removeAi: (name: string) => `${name} AI 제거`,
  },
  "en-US": {
    eyebrow: "An adventure together",
    room: "Room code",
    duration: "Preparation time",
    me: "You",
    players: "Your fellow trainers",
    spectators: "Spectators",
    human: "Trainer",
    invite: "Copy invite link",
    inviteHint: "Send the link to invite your friends.",
    readyCount: (ready: number, total: number) => `Ready ${ready}/${total}`,
    ownNotReady: "Press Ready when you are ready to join.",
    start: "Start game",
    returnToLobby: "Return to lounge",
    hostWaiting: "Invite friends and start when everyone is ready.",
    autoFill: "AI will fill the remaining spots at the start.",
    info: "Game guide",
    closeInfo: "View trainers",
    next: "Up next",
    empty: "Waiting for trainers.",
    joinTitle: "Join the lounge",
    createTitle: "Ready for an adventure?",
    joinHint: "Choose a name for your friends to see, then join them.",
    createHint: "Choose your name to open a lounge and invite friends.",
    enter: "Enter lounge",
    create: "Create lounge",
    back: "Back",
    pending: "Joining…",
    readyPending: "Updating readiness…",
    startPending: "Starting…",
    aiPending: "Updating AI…",
    stepLobby: "Lounge",
    stepPokemon: "Choose Pokémon",
    stepExplore: "Explore",
    spectatorHint: "You are spectating. Waiting for the participants.",
    removeAi: (name: string) => `Remove AI ${name}`,
  },
  "ja-JP": {
    eyebrow: "みんなで冒険",
    room: "ルームコード",
    duration: "探索の準備時間",
    me: "自分",
    players: "一緒に遊ぶトレーナー",
    spectators: "観戦者",
    human: "トレーナー",
    invite: "招待リンクをコピー",
    inviteHint: "リンクを送って友達を招待しましょう。",
    readyCount: (ready: number, total: number) => `準備 ${ready}/${total}`,
    ownNotReady: "遊ぶ準備ができたら「準備」を押してください。",
    start: "ゲーム開始",
    returnToLobby: "待機室に戻る",
    hostWaiting: "友達を招待して、全員の準備ができたら開始しましょう。",
    autoFill: "空いている枠は開始時にAIが参加します。",
    info: "ゲーム案内",
    closeInfo: "参加者を見る",
    next: "次のステップ",
    empty: "参加者を待っています。",
    joinTitle: "待機室に参加",
    createTitle: "冒険の準備をしよう",
    joinHint: "友達に表示する名前を決めて参加しましょう。",
    createHint: "名前を決めると、友達を招待できる待機室が開きます。",
    enter: "待機室に入る",
    create: "待機室を作る",
    back: "戻る",
    pending: "参加中…",
    readyPending: "準備を反映中…",
    startPending: "開始中…",
    aiPending: "AIを反映中…",
    stepLobby: "待機室",
    stepPokemon: "ポケモン選択",
    stepExplore: "探索開始",
    spectatorHint: "観戦中です。参加者の準備を待っています。",
    removeAi: (name: string) => `AI ${name}を外す`,
  },
};

export function getRoomLobbyCopy(locale: string) {
  return copy[resolvePokeLoungeLocale(locale)];
}
